<?php

namespace Database\Seeders;

use App\Models\Client;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clients = [
            [
                'name' => 'Costruzioni Rossi S.p.A.',
                'address' => 'Via Roma 123',
                'city' => 'Milano',
                'postal_code' => '20100',
                'province' => 'MI',
                'email' => 'info@costruzionirossi.it',
                'phone' => '02 1234567',
                'vat_number' => 'IT12345678901',
                'fiscal_code' => 'RSSMRA80A01F205Z',
                'notes' => 'Cliente storico dal 2010',
            ],
            [
                'name' => 'Edilizia Bianchi S.r.l.',
                'address' => 'Corso Italia 45',
                'city' => 'Roma',
                'postal_code' => '00100',
                'province' => 'RM',
                'email' => 'amministrazione@ediliziabianchi.it',
                'phone' => '06 7654321',
                'vat_number' => 'IT09876543210',
                'fiscal_code' => 'BNCGPP75B02H501Y',
                'notes' => 'Specializzati in ristrutturazioni',
            ],
            [
                'name' => 'Impresa Verdi & Figli',
                'address' => 'Via Napoli 78',
                'city' => 'Torino',
                'postal_code' => '10100',
                'province' => 'TO',
                'email' => 'contatti@impresaverdi.com',
                'phone' => '011 9876543',
                'vat_number' => 'IT45678901234',
                'fiscal_code' => 'VRDLCA68C03L219X',
                'notes' => 'Azienda familiare',
            ],
            [
                'name' => 'Costruzioni Moderne S.r.l.',
                'address' => 'Via Garibaldi 56',
                'city' => 'Bologna',
                'postal_code' => '40100',
                'province' => 'BO',
                'email' => 'info@costruzionimoderne.it',
                'phone' => '051 2345678',
                'vat_number' => 'IT34567890123',
                'fiscal_code' => 'MDRNTN72D04A944Z',
                'notes' => 'Specializzati in edifici commerciali',
            ],
            [
                'name' => 'Fratelli Neri Costruzioni',
                'address' => 'Viale Europa 89',
                'city' => 'Firenze',
                'postal_code' => '50100',
                'province' => 'FI',
                'email' => 'amministrazione@fratellineri.it',
                'phone' => '055 8765432',
                'vat_number' => 'IT23456789012',
                'fiscal_code' => 'NREFNC70E05D612W',
                'notes' => 'Specializzati in restauri storici',
            ],
            [
                'name' => 'Impresa Esposito S.p.A.',
                'address' => 'Via Vesuvio 12',
                'city' => 'Napoli',
                'postal_code' => '80100',
                'province' => 'NA',
                'email' => 'info@impresaesposito.it',
                'phone' => '081 3456789',
                'vat_number' => 'IT56789012345',
                'fiscal_code' => 'SPSGNN65F06F839X',
                'notes' => 'Attivi nel settore dal 1980',
            ],
            [
                'name' => 'Costruzioni Ferrara S.r.l.',
                'address' => 'Via Dante 34',
                'city' => 'Palermo',
                'postal_code' => '90100',
                'province' => 'PA',
                'email' => 'ufficio@costruzioniferrara.it',
                'phone' => '091 4567890',
                'vat_number' => 'IT67890123456',
                'fiscal_code' => 'FRRLGU77G07G273Y',
                'notes' => 'Specializzati in opere pubbliche',
            ],
            [
                'name' => 'Edil Romano & C.',
                'address' => 'Via Marconi 67',
                'city' => 'Genova',
                'postal_code' => '16100',
                'province' => 'GE',
                'email' => 'contabilita@edilromano.com',
                'phone' => '010 5678901',
                'vat_number' => 'IT78901234567',
                'fiscal_code' => 'RMNPLA69H08D969Z',
                'notes' => 'Specializzati in ristrutturazioni marittime',
            ],
            [
                'name' => 'Martini Costruzioni S.p.A.',
                'address' => 'Corso Vittorio Emanuele 90',
                'city' => 'Bari',
                'postal_code' => '70100',
                'province' => 'BA',
                'email' => 'info@martinicostruzioni.it',
                'phone' => '080 6789012',
                'vat_number' => 'IT89012345678',
                'fiscal_code' => 'MRTSVT71I09A662X',
                'notes' => 'Specializzati in infrastrutture',
            ],
            [
                'name' => 'Impresa Ricci S.r.l.',
                'address' => 'Via Mazzini 23',
                'city' => 'Venezia',
                'postal_code' => '30100',
                'province' => 'VE',
                'email' => 'amministrazione@impresaricci.it',
                'phone' => '041 7890123',
                'vat_number' => 'IT90123456789',
                'fiscal_code' => 'RCCMRC73L10L736Z',
                'notes' => 'Specializzati in restauri acquatici',
            ],
            [
                'name' => 'Costruzioni Moretti & Figli',
                'address' => 'Via Cavour 45',
                'city' => 'Cagliari',
                'postal_code' => '09100',
                'province' => 'CA',
                'email' => 'info@costruzionimoretti.com',
                'phone' => '070 8901234',
                'vat_number' => 'IT01234567890',
                'fiscal_code' => 'MRTGPP74M11B354Z',
                'notes' => 'Azienda familiare dal 1975',
            ],
            [
                'name' => 'Edilizia Conti S.p.A.',
                'address' => 'Viale Trieste 78',
                'city' => 'Padova',
                'postal_code' => '35100',
                'province' => 'PD',
                'email' => 'segreteria@ediliziaconti.it',
                'phone' => '049 9012345',
                'vat_number' => 'IT12345098765',
                'fiscal_code' => 'CNTFBA76N12G224Z',
                'notes' => 'Specializzati in edifici residenziali',
            ],
            [
                'name' => 'Fratelli Gallo Costruzioni',
                'address' => 'Via Piave 56',
                'city' => 'Verona',
                'postal_code' => '37100',
                'province' => 'VR',
                'email' => 'info@fratelligallo.it',
                'phone' => '045 0123456',
                'vat_number' => 'IT23456098765',
                'fiscal_code' => 'GLLNTN77P13L781Z',
                'notes' => 'Specializzati in restauri storici',
            ],
            [
                'name' => 'Impresa Marini S.r.l.',
                'address' => 'Corso Umberto I 34',
                'city' => 'Catania',
                'postal_code' => '95100',
                'province' => 'CT',
                'email' => 'amministrazione@impresamarini.com',
                'phone' => '095 1234567',
                'vat_number' => 'IT34567098765',
                'fiscal_code' => 'MRNLCU78Q14C351Z',
                'notes' => 'Specializzati in costruzioni antisismiche',
            ],
            [
                'name' => 'Costruzioni Vitale S.p.A.',
                'address' => 'Via Colombo 67',
                'city' => 'Messina',
                'postal_code' => '98100',
                'province' => 'ME',
                'email' => 'info@costruzionivitale.it',
                'phone' => '090 2345678',
                'vat_number' => 'IT45678098765',
                'fiscal_code' => 'VTLGNN79R15F158Z',
                'notes' => 'Specializzati in opere marittime',
            ],
            [
                'name' => 'Edil Lombardi & C.',
                'address' => 'Via Diaz 89',
                'city' => 'Parma',
                'postal_code' => '43100',
                'province' => 'PR',
                'email' => 'contatti@edillombardi.com',
                'phone' => '0521 3456789',
                'vat_number' => 'IT56789098765',
                'fiscal_code' => 'LMBDVD80S16G337Z',
                'notes' => 'Specializzati in edifici industriali',
            ],
            [
                'name' => 'Impresa Fabbri S.r.l.',
                'address' => 'Viale Matteotti 12',
                'city' => 'Modena',
                'postal_code' => '41100',
                'province' => 'MO',
                'email' => 'info@impresafabbri.it',
                'phone' => '059 4567890',
                'vat_number' => 'IT67890987654',
                'fiscal_code' => 'FBBMTT81T17F257Z',
                'notes' => 'Specializzati in edifici commerciali',
            ],
            [
                'name' => 'Costruzioni Greco S.p.A.',
                'address' => 'Via Garibaldi 34',
                'city' => 'Reggio Calabria',
                'postal_code' => '89100',
                'province' => 'RC',
                'email' => 'amministrazione@costruzionigreco.com',
                'phone' => '0965 5678901',
                'vat_number' => 'IT78909876543',
                'fiscal_code' => 'GRCSFN82U18H224Z',
                'notes' => 'Specializzati in infrastrutture pubbliche',
            ],
            [
                'name' => 'Edilizia De Luca S.r.l.',
                'address' => 'Corso Vittorio Emanuele 56',
                'city' => 'Salerno',
                'postal_code' => '84100',
                'province' => 'SA',
                'email' => 'info@ediliziadeluca.it',
                'phone' => '089 6789012',
                'vat_number' => 'IT89098765432',
                'fiscal_code' => 'DLCGPP83V19I483Z',
                'notes' => 'Specializzati in ristrutturazioni',
            ],
            [
                'name' => 'Fratelli Santoro Costruzioni',
                'address' => 'Via Roma 78',
                'city' => 'Perugia',
                'postal_code' => '06100',
                'province' => 'PG',
                'email' => 'info@fratellisantoro.com',
                'phone' => '075 7890123',
                'vat_number' => 'IT90987654321',
                'fiscal_code' => 'SNTLCA84Z20G478Z',
                'notes' => 'Azienda familiare dal 1990',
            ],
        ];

        foreach ($clients as $client) {
            Client::create($client);
        }
    }
}