name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.AGENDA_DEPLOY }}
          script: |
            cd /var/www/html/edilcipriano

            echo "🔄 Pulling latest code"
            git pull origin main

            echo "📦 Installing backend dependencies"
            composer install --no-interaction --prefer-dist --optimize-autoloader

            echo "📦 Installing front-end dependencies"
            npm install

            echo "🛠 Building assets"
            npm run build

            echo "🗄 Running migrations"
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan optimize

            echo "🧹 Clearing caches"
            php artisan optimize:clear
            php artisan cache:clear

            echo "📦 Restarting  nginx"
            sudo nginx -t && sudo systemctl reload nginx

            echo "🧷 Setting permissions"
            sudo chown -R peels:www-data /var/www/html/edilcipriano
            sudo chmod -R 755 /var/www/html/edilcipriano
            sudo chmod -R 775 /var/www/html/edilcipriano/storage
            sudo chmod -R 775 /var/www/html/edilcipriano/bootstrap/cache
            sudo chmod -R 755 /var/www/html/edilcipriano/public

            echo "✅ Deployment finished"
